name: Build user scripts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
      
      - name: Build all packages
        run: npm run build:prod

      - name: Setup git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: build-result

      - name: Deploy built files to result branch
        run: |
          git add -f userscript
          git commit -m "Build and deploy to build-result"
          git push origin build-result --force